In [17]:
from time import time
import numpy as np


def matrix(n):
    tiempo_inicial = time()    
    A = np.mat(np.full((n, n), 1, dtype=int))
    B = np.mat(np.full((n, n), 2, dtype=int))
    tiempo_final = time()
    print( (tiempo_final - tiempo_inicial))
    print( A*B)

In [19]:
matrix(4)

0.0
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
